swagger: "2.0"
info:
  description: "Collection Offer Details"
  version: "1.0.0"
  title: "Collection Customer Details"
host: "172.16.125.27:39081"
basePath: "/v1"
tags:
- name: "fetchOfferEligibility"
  description: "Provide details related to a customer collection"
schemes:
- "http"
paths:
  /fetchOfferEligibility:
    post:
      tags:
      - "fetchOfferEligibility"
      summary: "Check for moratorium and provide the details of customer account number"
      description: "Moratarium Database will be scanned for the account number and post the data is collected operation will be performed to findout the details of the customer account number"
      operationId: "Fetch Moratorium Database and process the data"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "CollectionCustDtlsRqVO"
        required: true
        schema:
          $ref: "#/definitions/CollectionCustDtlsRqList"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Response"
        "405":
          description: "Invalid input"
          
definitions:
  CollectionCustDtlsRqList:
    type: array
    items:
      $ref: '#/definitions/CollectionCustDtlsRqVO'
  CollectionCustDtlsRqVO:
    type: "object"
    required:
    - "acctNumber"
    - "cd"
    - "intStatus"
    - "channelId"
    - "txnId"
    - "timeStamp"
    properties:
      acctNumber:
        type: "string"
      cd:
        type: "string"
      acctblock1:
        type: "string"
      acctblock2:
        type: "string"
      intStatus:
        type: "string"
      channelId:
        type: "string"
        enum: [WEBSITE,ILA,MOBILE,IVR]
      txnId: 
        type: "string"
      timeStamp:
        type: "string"
        
  Response:
    type: object
    properties:
      responseObj:
        $ref: '#/definitions/CollectionCustDtlsRsList'
      status:
        $ref: '#/definitions/Status'
        
  Status:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
      bussinessErrorCode:
        type: string
      bussinessDescription:
        type: string
        
  CollectionCustDtlsRsList:
    type: array
    items:
      properties:
        txnId:
          type: string 
          example: "AX123VBAZURDS"
        acctNumber:
          type: string
          example: "501826633728"
        moraOptInFlg:
          type: string
          enum: [Y,N]
          example: Y
        delqType:
          type: "string"
          enum: [MORA-NODELQ,NOMORA-NODELQ,DELQ-MORA,EARLY-DELQ,MID-DELQ,LATE-DELQ,CHARGED-OFF]
          example: CHARGED-OFF
        delqState:
          type: "string"
          enum: [MORA-OPTED,NON-DELINQUENT,DELINQUENT,SEVERELY-DELINQUENT,WRITE-OFF]
          example: WRITE-OFF
        offerEligibility:
          $ref: '#/definitions/OfferEligibility'
          
  OfferEligibility:
    type: object
    properties:
      prdBalCon:
        type: string
        enum: [Y,N]
        example: N
      prdStlmnt:
        type: string
        enum: [Y,N]
        example: Y
      prdReinst:
        type: string
        enum: [Y,N]
        example: N
      prdRestruct:
        type: string
        enum: [Y,N]
        example: Y
      prdOther1:
        type: string
        enum: [Y,N]
        example: N
      prdOther2:
        type: string
        enum: [Y,N]
        example: Y
      prdOther3:
        type: string
        enum: [Y,N]
        example: N
      prdOther4:
        type: string
        enum: [Y,N]
        example: Y
      prdStlmntOfferExists:
        type: string
        enum: [Y,N]
        example: Y
      prdReinstOfferExists:
        type: string
        enum: [Y,N]
        example: Y  
      prdRestructOfferExists:
        type: string
        enum: [Y,N]
        example: Y
      prdOther2OfferExists:
        type: string
        enum: [Y,N]
        example: Y
      prdOther1OfferExists:
        type: string
        enum: [Y,N]
        example: Y        
      prdOther3OfferExists:
        type: string
        enum: [Y,N]
        example: Y
      prdOther4OfferExists:
        type: string
        enum: [Y,N]
        example: Y
      prdBalConOfferExists:
        type: string
        enum: [Y,N]
        example: Y  